// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tenant-app/Current.tsx": () => import("../components/mockups/tenant-app/Current.tsx"),
  "./components/mockups/tenant-app/LandlordRedesigned.tsx": () => import("../components/mockups/tenant-app/LandlordRedesigned.tsx"),
  "./components/mockups/tenant-app/Redesigned.tsx": () => import("../components/mockups/tenant-app/Redesigned.tsx")
};
